Some cleanups

diff --git a/packages/gfm-preview/gfm-preview b/packages/gfm-preview/gfm-preview
--- a/packages/gfm-preview/gfm-preview
+++ b/packages/gfm-preview/gfm-preview
@@ -5,65 +5,57 @@
 # and therefore supports only one active client.
 
 usage() {
-	echo "Usage: $(basename "$0") [-p PORT] <FILE>"
+	>&2 echo "Usage: $(basename "$0") [-p PORT] <FILE>"
 	exit 1
 }
 
 port=8080
 while getopts p: name; do
 	case $name in
-		p) port="$OPTARG";;
-		?) usage;;
+		p) port=$OPTARG ;;
+		?) usage ;;
 	esac
 done
 shift $((OPTIND - 1))
 
 file=${1:-README.md}
-[ -f "$file" ] || { echo "$0: file $file not found"; usage; }
+[ -f "$file" ] || { >&2 echo "$0: file $file not found"; usage; }
 
 path=$(dirname "$file")
-repo=$(git -C "$path" remote 2>/dev/null \
-		   | xargs -rd'\n' -L1 git -C "$path" remote get-url \
-		   | sed -nz 's/.*github.com:\([^/]\+\/[^.]\+\).*/\1/p')
+repo=$(git -C "$path" remote 2>/dev/null |
+		   xargs -rd'\n' -L1 git -C "$path" remote get-url |
+		   sed -nz 's/.*github.com:\([^/]\+\/[^.]\+\).*/\1/p')
 [ "$repo" ] && echo "Repository: $repo"
 
 render() {
 	echo '<!DOCTYPE html>'
-	[ "$repo" ] \
-		&& echo "<head><base href=\"https://github.com/$repo/raw/HEAD/\"></head>"
-
-	curl --silent --show-error -X POST \
-		 -H "Accept: application/vnd.github.v3+json" \
-		 https://api.github.com/markdown \
+	[ "$repo" ] &&
+		echo "<head><base href=\"https://github.com/$repo/raw/HEAD/\"></head>"
+	curl --silent --show-error --location -H 'Accept: application/vnd.github+json' \
 		 --data-binary "$(<"$file" jq --raw-input --slurp --compact-output \
 			 --arg repo "$repo" \
-			 '{text: ., mode: "gfm"} | if $repo == "" then . else .context |= $repo end')"
+			 '{text: ., mode: "gfm"} | if $repo != "" then .context = $repo end')" \
+		 https://api.github.com/markdown
 }
 
 process_request() {
 	read -r _method path _protocol
-	# Read request headers
-	while
-		read -r z
-		[ ${#z} -gt 2 ]
-	do :; done
+	while read -r z; [ ${#z} -gt 2 ]; do :; done # Read request headers
 
-	if ! [ -f "$tmp"/out ] \
-			|| timeout 15s fswatch -1 --event Updated "$file" >/dev/null; then
+	if ! [ -e "$tmp"/out ] ||
+			timeout 15s fswatch -1 --event Updated "$file" >/dev/null; then
 		{ render; echo '<script>(async function() { for (;;) {
 let res = await fetch(location);
 if (res.ok) document.documentElement.innerHTML = await res.text();
 } })()</script>'; } >"$tmp"/out
 	fi
 
-	printf %b "HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: $(wc -c <"$tmp"/out)\r\n\r\n"
+	printf 'HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: %u\r\n\r\n' "$(wc -c <"$tmp"/out)"
 	cat "$tmp"/out
 }
 
-tmp=$(mktemp -d) \
-	|| { >&2 echo "Failed to create tmp directory!"; exit 1; }
-# shellcheck disable=SC2064 # Want the current value of tmp
-trap "rm -r '$tmp'" EXIT
+tmp=$(mktemp -d) || { >&2 echo "Failed to create temporary directory"; exit 1; }
+trap 'rm -rf -- "$tmp"' EXIT
 mkfifo "$tmp"/pipe
 
 xdg-open localhost:"$port"
@@ -71,5 +63,5 @@ xdg-open localhost:"$port"
 echo "Listening on http://localhost:$port/"
 while
 	# shellcheck disable=SC2094 # The file is a named pipe
-	nc -l "$port" <"$tmp"/pipe | process_request >"$tmp"/pipe
+	<"$tmp"/pipe nc -l "$port" | process_request >"$tmp"/pipe
 do :; done
diff --git a/packages/git-absorb/git-absorb b/packages/git-absorb/git-absorb
--- a/packages/git-absorb/git-absorb
+++ b/packages/git-absorb/git-absorb
@@ -4,18 +4,16 @@
 
 shopt -s lastpipe nullglob
 
-boundary=$(git rev-parse "${1:-HEAD~5}" 2>/dev/null) || boundary=
+boundary=$(git rev-parse "${1:-HEAD~5}" 2>/dev/null)
 fixupped_commit() {
 	git blame --incremental -L "$2" "$boundary".. -- "$1" | IFS=\  read -r hash _
 	[[ $hash != "$boundary" ]]
 }
 
-tmp=$(mktemp -d) || { echo 'Failed to create temporary directory'; exit 1; }
-# shellcheck disable=SC2064
-trap "rm -rf -- '$tmp'" EXIT
+tmp=$(mktemp -d) || { >&2 echo 'Failed to create temporary directory'; exit 1; }
+trap 'rm -rf -- "$tmp"' EXIT
 
-git diff-index --cached --unified=0 --no-prefix --ignore-submodules HEAD \
-	| while :; do
+git diff-index --cached --unified=0 --no-prefix --ignore-submodules HEAD | while :; do
 	while IFS=\  read -r ext_header
 		  case $ext_header in '') break 2 ;; 'index '*) false; esac
 	do :; done
@@ -34,7 +32,7 @@ git diff-index --cached --unified=0 --no-prefix --ignore-submodules HEAD \
 +++ b/$b
 EOF
 		patched[$hash]=1
-		{ echo "$line"; printf '%s' "${hunk[@]}"; } >>"$tmp/$hash"
+		printf %s\\n%s "$line" "${hunk[@]}" >>"$tmp/$hash"
 	done
 done
 
diff --git a/packages/open-csb-door/open-csb-door b/packages/open-csb-door/open-csb-door
--- a/packages/open-csb-door/open-csb-door
+++ b/packages/open-csb-door/open-csb-door
@@ -3,15 +3,15 @@
 
 if test ! -t 0; then
 	# Read from stdin
-	IFS= read -r username && IFS= read -r password \
-		&& { door_id=$1; [ "$door_id" ] || IFS= read -r door_id; }
+	IFS= read -r username && IFS= read -r password &&
+		{ door_id=$1; [ "$door_id" ] || IFS= read -r door_id; }
 elif command -v kwallet-query >/dev/null; then
 	username=$(kwallet-query --folder chalmersstudentbostader.se --read-password username kdewallet) \
 		&& password=$(kwallet-query --folder chalmersstudentbostader.se --read-password password kdewallet) \
 		&& door_id=${1:-$(kwallet-query --folder chalmersstudentbostader.se --read-password door-id kdewallet)}
 else
 	false
-fi || { echo 'Failed to read passwords!'; exit 1; }
+fi || { >&2 echo 'Failed to read passwords.'; exit 1; }
 
 cookies=$(mktemp) || { >&2 echo 'Failed to create cookie-jar.'; exit 1; }
 trap 'rm -f -- "$cookies"' EXIT
@@ -21,30 +21,30 @@ redirect_url=$(curl --fail --no-progress-meter \
 	--cookie "$cookies" --cookie-jar "$cookies" \
 	--data "log=$username" --data "pwd=$password" \
 	--location --output /dev/null --write-out %{url_effective} \
-	https://www.chalmersstudentbostader.se/wp-login.php) \
-		 || { >&2 echo 'Login to CSB failed.'; exit 1; }
+	https://www.chalmersstudentbostader.se/wp-login.php) ||
+	{ >&2 echo 'Login to CSB failed.'; exit 1; }
 case $redirect_url in
-	*'/login/?err=login') echo 'Invalid credentials!'; exit 1 ;;
+	*'/login/?err=login') >&2 echo 'Invalid credentials!'; exit 1 ;;
 esac
 
 # Returns the URL for authenticating to Aptus.
 get_aptus_url() {
 	resp=$(curl --fail --no-progress-meter \
 				--cookie "$cookies" --cookie-jar "$cookies" \
-				'https://www.chalmersstudentbostader.se/widgets/?callback=&widgets[]=aptuslogin@APTUSPORT') \
-		|| { >&2 echo 'Could not fetch Aptus login URL.'; return 1; }
+				'https://www.chalmersstudentbostader.se/widgets/?callback=&widgets[]=aptuslogin@APTUSPORT') ||
+		{ >&2 echo 'Could not fetch Aptus login URL.'; return 1; }
 	resp=${resp#'('}; resp=${resp%');'} # Remove surrounding "(...);"
-	url=$(echo "$resp" | jq --raw-output \
-							'.data."aptuslogin@APTUSPORT".objekt|.[0].aptusUrl') \
-	   || { >&2 echo 'Failed to parse Aptus login URL.'; return 1; }
+	url=$(echo "$resp" |
+			  jq --raw-output '.data."aptuslogin@APTUSPORT".objekt.[0].aptusUrl') ||
+		{ >&2 echo 'Failed to parse Aptus login URL.'; return 1; }
 	echo "$url" | sed 's/ /%20/g'
 }
 
 # Authenticate to Aptus and request to open door
 aptus_url=$(get_aptus_url) || exit $?
 
-curl --fail --fail-early --output /dev/null --no-progress-meter --location \
+curl --fail --fail-early --no-progress-meter --location \
 	 --cookie "$cookies" --cookie-jar "$cookies" \
-	 "$aptus_url" \
-	 "https://apt-www.chalmersstudentbostader.se/AptusPortal/Lock/UnlockEntryDoor/$door_id" \
-	 || { >&2 echo 'Requests to authenticate to Aptus and unlock entrance failed.'; exit 1; }
+	 --output /dev/null "$aptus_url" \
+	 "https://apt-www.chalmersstudentbostader.se/AptusPortal/Lock/UnlockEntryDoor/$door_id" ||
+	{ >&2 echo 'Requests to authenticate to Aptus and unlock entrance failed.'; exit 1; }
diff --git a/packages/spotify-mix-playlists/spotify-mix-playlists b/packages/spotify-mix-playlists/spotify-mix-playlists
--- a/packages/spotify-mix-playlists/spotify-mix-playlists
+++ b/packages/spotify-mix-playlists/spotify-mix-playlists
@@ -2,34 +2,35 @@
 # Creates Spotify playlists by combining those of a given user.
 
 if [ -z "$CLIENT_ID" ] || [ -z "$CLIENT_SECRET" ]; then
-	echo 'Missing CLIENT_ID or CLIENT_SECRET. Exiting...'
+	>&2 echo 'Missing CLIENT_ID or CLIENT_SECRET. Exiting...'
 	exit 1
 fi
 
-user_id="$1"
-[ "$user_id" ] || { echo 'Missing argument user_id. Exiting...'; exit 1; }
+user_id=$1
+[ "$user_id" ] || { >&2 echo 'Missing argument user_id. Exiting...'; exit 1; }
 
 if ! [ "$REFRESH_TOKEN" ]; then
-	redirect_uri="http://$(dig +short myip.opendns.com @resolver1.opendns.com)/"
-	echo "To obtain refresh token, port forward port 80 and open:
+	redirect_uri=http://$(dig +short myip.opendns.com @resolver1.opendns.com)/
+	>&2 echo "To obtain refresh token, port forward port 80 and open:
 
     https://accounts.spotify.com/authorize?client_id=$CLIENT_ID&response_type=code&redirect_uri=$redirect_uri&scope=playlist-modify-public
 
 Starting netcat for monitoring redirect URI callbacks after authentication success or failure:"
 	trap : INT; sudo nc -kl 80; trap - INT
 	printf 'Enter authorization code: '; read -r code
-	curl -X POST https://accounts.spotify.com/api/token \
+	curl https://accounts.spotify.com/api/token \
 		 -H "Authorization: Basic $(printf "%s:%s" "$CLIENT_ID" "$CLIENT_SECRET" | base64 --wrap=0)" \
 		 -d grant_type=authorization_code -d code="$code" -d redirect_uri="$redirect_uri"
 	exit 1
 fi
 
-powerset() { [ $# -gt 0 ] && { shift; powerset "$@"; } \
-				 | while read -r a; do
-				 echo "$1" "$a"
-				 echo "$a"
-			 done \
-				 || echo; }
+powerset() {
+	[ $# -gt 0 ] && { shift; powerset "$@"; } |
+		while read -r a; do
+			echo "$1" "$a"
+			echo "$a"
+		done || echo
+}
 
 # Gets all Spotify track URIs of a playlist separated by newlines:
 #
@@ -38,14 +39,13 @@ powerset() { [ $# -gt 0 ] && { shift; powerset "$@"; } \
 # where playlist is the Spotify ID for the playlist.
 playlist_tracks() {
 	# API endpoint for next page of items
-	next="https://api.spotify.com/v1/playlists/$1/tracks"
+	next=https://api.spotify.com/v1/playlists/$1/tracks
 	while
-		items=$(curl -X GET "$next" \
-					 -H "Authorization: Bearer $access_token" \
-					 --silent --show-error)
+		items=$(curl --silent --show-error "$next" \
+					 -H "Authorization: Bearer $access_token")
 		echo "$items" | jq --raw-output '.items[] | select(.track) | .track.uri'
 
-		next=$(echo "$items" | jq --raw-output --exit-status '.next')
+		next=$(echo "$items" | jq --raw-output --exit-status .next)
 	do :; done
 }
 
@@ -63,7 +63,7 @@ set_playlist_tracks() {
 			 -H "Authorization: Bearer $access_token" \
 			 --data "$(jq --null-input --compact-output \
 			 --arg tracks "$chunk" '{uris: $tracks | split("\n")}')" \
-			 -H "Content-Type: application/json" \
+			 -H 'Content-Type: application/json' \
 			 --silent --show-error >/dev/null # Ignore snapshot_id result
 		first=false
 	done
@@ -71,45 +71,45 @@ set_playlist_tracks() {
 
 # Enter temporary directory for saving playlist information
 # shellcheck disable=SC2015 # actually want to exit if either mktemp/cd fails
-tmp=$(mktemp -d) && cd "$tmp" \
-		|| { echo 'cd into temporary directory failed. Exiting...'; exit 1; }
+tmp=$(mktemp -d) && cd "$tmp" ||
+		{ echo 'cd into temporary directory failed. Exiting...'; exit 1; }
 
 # Get the access token for the app: Needed to access public content
-access_token=$(curl -X POST https://accounts.spotify.com/api/token \
+access_token=$(curl --silent --show-error \
 	-H "Authorization: Basic $(printf "%s:%s" "$CLIENT_ID" "$CLIENT_SECRET" | base64 --wrap=0)" \
-	-d grant_type=client_credentials \
-	--silent --show-error \
-	| jq --raw-output '.access_token')
+	--data grant_type=client_credentials \
+	https://accounts.spotify.com/api/token |
+	jq --raw-output .access_token)
 
 # Fetch all playlists
-playlists=$(curl -X GET "https://api.spotify.com/v1/users/$user_id/playlists" \
+playlists=$(curl --silent --show-error \
 	-H "Authorization: Bearer $access_token" \
-	--silent --show-error \
-	| jq --raw-output '.items[] | "\(.id) \(.name)"')
+	"https://api.spotify.com/v1/users/$user_id/playlists" |
+	jq --raw-output '.items[] | "\(.id) \(.name)"')
 printf "Mixing these playlists from user %s:\n%s\n\n" "$user_id" "$playlists"
 
 # Fetch all tracks in the playlists
 echo "$playlists" | while read -r id name; do
 	mkdir "$id" # Create directory for the playlist in question
-	echo "$name" > "$id/name" # Store the playlist name in a file
-	playlist_tracks "$id" > "$id/tracks" # Store tracks in other file
+	echo "$name" >"$id/name" # Store the playlist name in a file
+	playlist_tracks "$id" >"$id/tracks" # Store tracks in other file
 done
 
 # Request a refreshed access token for setting mixed playlists
-access_token=$(curl -X POST https://accounts.spotify.com/api/token \
+access_token=$(curl --silent --show-error \
 	-H "Authorization: Basic $(printf "%s:%s" "$CLIENT_ID" "$CLIENT_SECRET" | base64 --wrap=0)" \
-	-d grant_type=refresh_token -d refresh_token="$REFRESH_TOKEN" \
-	--silent --show-error \
-	| jq --raw-output '.access_token')
-user_id=$(curl -X GET https://api.spotify.com/v1/me \
+	--data grant_type=refresh_token --data refresh_token="$REFRESH_TOKEN" \
+	https://accounts.spotify.com/api/token |
+	jq --raw-output .access_token)
+user_id=$(curl --silent --show-error \
 	-H "Authorization: Bearer $access_token" \
-	--silent --show-error \
-	| jq --raw-output '.id')
+	https://api.spotify.com/v1/me |
+	jq --raw-output .id)
 # Fetch existing aggregate playlists to avoid creating duplicates
-existing=$(curl -X GET "https://api.spotify.com/v1/users/$user_id/playlists" \
+existing=$(curl --silent --show-error \
 	-H "Authorization: Bearer $access_token" \
-	--silent --show-error \
-	| jq --raw-output '.items[] | "\(.id) \(.name)"')
+	"https://api.spotify.com/v1/users/$user_id/playlists" |
+	jq --raw-output '.items[] | "\(.id) \(.name)"')
 
 # For the powerset of the set of all playlists
 # shellcheck disable=SC2035 # the function does not take any options
@@ -128,17 +128,17 @@ powerset * | while read -r first second third rest; do
 		echo "Found existing $new_id"
 	else
 		# Otherwise: Create a new playlist
-		new_id=$(curl -X POST "https://api.spotify.com/v1/users/$user_id/playlists" \
+		new_id=$(curl --silent --show-error \
 					  -H "Authorization: Bearer $access_token" \
 					  --data "$(echo "$combined_name" | jq --raw-input --null-input \
-					  'input as $name | {name: $name, description: "Nice combined playlist!"}')" \
+					  'input as $name | {name: $name, description: "Combined playlist"}')" \
 					  -H "Content-Type: application/json" \
-					  --silent --show-error \
-					 | jq --raw-output '.id')
+					  "https://api.spotify.com/v1/users/$user_id/playlists" |
+					 jq --raw-output .id)
 	fi
 
 	# Concatenate tracks of all playlists
 	# shellcheck disable=SC2046 # ids do not have any spaces
-	cat -- $(for id in $line; do printf "%s/tracks " "$id"; done) \
-		| set_playlist_tracks "$new_id"
+	cat -- $(for id in $line; do printf '%s/tracks ' "$id"; done) |
+		set_playlist_tracks "$new_id"
 done
